/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;


public class App {
    public String getGreeting() { return "Hello World!"; }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //fileDemoReaderResourceFolder();


        String inputFileName ="C:/Users/ayoos/bitmap-transformer/app/src/main/resources/Hourglass.bmp";
        String outputFileName ="C:/Users/ayoos/bitmap-transformer/app/src/main/resources/AYA.bmp";
        String transformationName = "invertImage" ;

        bitmapLab Hourglass = new bitmapLab(inputFileName , outputFileName, transformationName);
    }
}
