/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;

// way 1: Colored image to Negative image conversion
public class App {

    public static void main(String[] args) {

        String input ="C:/Users/ayoos/bitmap-transformer/app/src/main/resources/Hourglass.bmp";
        String output ="C:/Users/ayoos/bitmap-transformer/app/src/main/resources/AYA.bmp";
        bitmapLab img = new bitmapLab();


        img.read(input);
//        img.conversionImage();
        img.brighterImage();
        img.write(output);

    }
}
